server:
  port: 8083
spring:
  application.name: emergency-notification-agent
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  profiles:
    active: int
rabbitmq:
  consuming-queue: emergency-data-collector
  producing-queue: notification-channel

