eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sportser
    username: root
    password: toto
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
