eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.2:8761/eureka


spring:
  datasource:
    url: jdbc:mysql://192.168.1.20:3306/sportser
    username: toto
    password: toto
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
