eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://172.31.253.254:5432/sportser_emergency
    username: postgres
    password: root
  jpa:
    hibernate:
      use-new-id-generator-mappings: false

  kafka:
    bootstrap-servers: 172.31.253.254:9092
    producer:
      group-id: hr-data-analyzer-prod
      topic: emergency-data-topic
    consumer:
      group-id: hr-data-analyzer
      topic: heart-rates-topic
    retry:
      topic:
        attempts: 3


address:
  user-profile: localhost
