eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  datasource:
    url: jdbc:postgresql://172.31.253.254:5432/sportser
    username: postgres
    password: root
  jpa:
    hibernate:
      use-new-id-generator-mappings: false

  kafka:
    bootstrap-servers: 172.31.253.254:9092
    producer:
      topic: coach-presence-topic
    retry:
      topic:
        attempts: 3
