FROM openjdk:17-jdk-slim

EXPOSE 9084

ADD target/sportser-notification-channel-manager.jar sportser-notification-channel-manager.jar

ENTRYPOINT [ "java", "-jar", "sportser-notification-channel-manager.jar"]
