eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


heart-rate-sensor-data-collector:
  ribbon:
    listOfServers: http://localhost:8081/

notification-channel-manager:
  ribbon:
    listOfServers: http://localhost:9084/
