eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.2:8761/eureka

heart-rate-sensor-data-collector:
  ribbon:
    listOfServers: http://192.168.1.5:8081/

notification-channel-manager:
  ribbon:
    listOfServers: http://192.168.1.15:9084/