eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  kafka:
    bootstrap-servers: 172.31.253.254:9092
    consumer:
      group-id: emergency-notification-agent

    retry:
      topic:
        attempts: 3


app:
  kafka:
    topic:
      emergency-topic: emergency-data-topic
      coach-presence-topic: coach-presence-topic
redis:
  host: 172.31.253.254
  port: 6379